apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-copy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoapp-copy
  template:
    metadata:
      labels:
        app: demoapp-copy
    spec:
      containers:
        - name: demoapp-copy
          image: my-tricarobert/demoapp:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-appemoapp-copy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
